name: Check Incomplete

on:
  repository_dispatch:
    types: [core-changed, edge-changed]
  workflow_dispatch:
      
jobs:

  incomplete-core:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: statstrade-dev/statstrade-core
          token: ${{ secrets.GH_TOKEN }}
 
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}
        
      - name: List base incomplete
        run: > 
          docker run --network host 
          -v /var/run/docker.sock:/var/run/docker.sock 
          -v $(pwd):$(pwd) 
          -w $(pwd) 
          ghcr.io/zcaudate-xyz/infra-foundation-dev:ci lein incomplete


#  incomplete-edge:
#    runs-on: ubuntu-latest
#    timeout-minutes: 3
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        with:
#          repository: statstrade-dev/statstrade-edge
#          token: ${{ secrets.GH_TOKEN }}
# 
#      - name: Log into registry ${{ env.REGISTRY }}
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ secrets.GH_USER }}
#          password: ${{ secrets.GH_TOKEN }}
#        
#      - name: List base incomplete
#        run: > 
#          docker run --network host 
#          -v /var/run/docker.sock:/var/run/docker.sock 
#          -v $(pwd):$(pwd) 
#          -w $(pwd) 
#          ghcr.io/zcaudate-xyz/infra-foundation-dev:ci lein incomplete
