name: Run Local Build

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [core-changed, edge-changed, all]
  workflow_dispatch:

jobs:

  run-local:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps: 
      - name: Checkout foundation-base
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout foundation-embed
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-embed
          path: foundation-embed
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout foundation-fx
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-fx
          path: foundation-fx
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout foundation-web
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-web
          path: foundation-fx
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout statstrade-core
        uses: actions/checkout@v3
        with:
          repository: statstrade-dev/statstrade-core
          path: statstrade-core
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
          
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Run Tmux
        run: >
          docker run --rm 
          ghcr.io/zcaudate-xyz/infra-foundation-dev:ci 
          which tmux
        
      - name: Run Build
        run: >
          docker run --rm --network host -v $(pwd):$(pwd) -w $(pwd) 
          ghcr.io/zcaudate-xyz/infra-foundation-dev:ci 
          bash -c 'cd statstrade-core && make deps-checkouts && lein run-local'
