name: Supabase Database

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  reset_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1 # Use a specific version or latest
        with:
          version: latest # Or a specific version like '1.75.6'

      - name: Login to Supabase CLI (if interacting with a remote project)
        # This step is needed if you are resetting a *remote* Supabase project.
        # Ensure SUPABASE_ACCESS_TOKEN is set as a GitHub secret.
        run: supabase login --token "${{ secrets.TEST_SUPABASE_ACCESS_TOKEN }}"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.TEST_SUPABASE_ACCESS_TOKEN }}

      - name: Link Supabase project (if interacting with a remote project)
        # This step is needed if you are resetting a *remote* Supabase project.
        # Ensure SUPABASE_PROJECT_REF is set as a GitHub secret.
        run: supabase link --project-ref "${{ secrets.TEST_SUPABASE_ID }}"
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.TEST_SUPABASE_ID }}

      - name: Reset Supabase Database
        # Use --linked if resetting a remote project, otherwise it resets the local DB.
        # --no-backup can be used to prevent creating a backup before resetting.
        run: supabase db reset --linked --yes