name: Run Core Tests

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [core-changed, all]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  run-test-db:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 12

    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        ports:
          - 2375:2375
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
          
      - name: Checkout foundation-base
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout foundation-embed
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-embed
          path: foundation-embed
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout foundation-fx
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-fx
          path: foundation-fx
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout statstrade-core
        uses: actions/checkout@v3
        with:
          repository: statstrade-dev/statstrade-core
          path: statstrade-core
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Setup postgres
        run: docker run -d --rm --network host --name postgres -e "POSTGRES_DB=test-scratch" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_PORT=5432" -e "POSTGRES_USER=postgres" ghcr.io/zcaudate-xyz/infra-db:main
        
      - name: Run statsdb tests
        run: >
          docker run --rm --network host -v $(pwd):$(pwd) -w $(pwd) 
          ghcr.io/zcaudate-xyz/infra-foundation-dev:ci 
          bash -c 'cd statstrade-core && make setup-checkouts && lein test-db'

  run-test-net:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        ports:
          - 2375:2375
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
      - name: Checkout foundation-base
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout foundation-embed
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-embed
          path: foundation-embed
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout foundation-fx
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-fx
          path: foundation-fx
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout statstrade-core
        uses: actions/checkout@v3
        with:
          repository: statstrade-dev/statstrade-core
          path: statstrade-core
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Setup postgres
        run: docker run -d --rm --network host --name postgres -e "POSTGRES_DB=test-scratch" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_PORT=5432" -e "POSTGRES_USER=postgres" ghcr.io/zcaudate-xyz/infra-db:main
        
      - name: Run statsnet tests
        run: >
          docker run --rm --network host -v $(pwd):$(pwd) -w $(pwd) 
          ghcr.io/zcaudate-xyz/infra-foundation-dev:ci 
          bash -c 'cd statstrade-core && make setup-checkouts && lein test-net'

  run-test-link:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        ports:
          - 2375:2375
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro

    steps:
      - name: Checkout foundation-base
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-base
          path: foundation-base
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout foundation-embed
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-embed
          path: foundation-embed
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout foundation-fx
        uses: actions/checkout@v3
        with:
          repository: zcaudate-xyz/foundation-fx
          path: foundation-fx
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Checkout statstrade-core
        uses: actions/checkout@v3
        with:
          repository: statstrade-dev/statstrade-core
          path: statstrade-core
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Setup postgres
        run: docker run -d --rm --network host --name postgres -e "POSTGRES_DB=test-scratch" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_PORT=5432" -e "POSTGRES_USER=postgres" ghcr.io/zcaudate-xyz/infra-db:main
        
      - name: Run statslink tests
        run: >
          docker run --rm --network host -v $(pwd):$(pwd) -w $(pwd) 
          ghcr.io/zcaudate-xyz/infra-foundation-dev:ci 
          bash -c 'cd statstrade-core && make setup-checkouts && lein test-link'

#  run-test-iberia:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#
#    steps:
#      - name: Checkout foundation-base
#        uses: actions/checkout@v3
#        with:
#          repository: zcaudate-xyz/foundation-base
#          path: foundation-base
#          token: ${{ secrets.GH_TOKEN }}
#          
#      - name: Checkout foundation-embed
#        uses: actions/checkout@v3
#        with:
#          repository: zcaudate-xyz/foundation-embed
#          path: foundation-embed
#          token: ${{ secrets.GH_TOKEN }}
#          
#      - name: Checkout foundation-fx
#        uses: actions/checkout@v3
#        with:
#          repository: zcaudate-xyz/foundation-fx
#          path: foundation-fx
#          token: ${{ secrets.GH_TOKEN }}
#          
#      - name: Checkout statstrade-core
#        uses: actions/checkout@v3
#        with:
#          repository: statstrade-dev/statstrade-core
#          path: statstrade-core
#          token: ${{ secrets.GH_TOKEN }}
#          
#      - name: Log into registry ${{ env.REGISTRY }}
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ secrets.GH_USER }}
#          password: ${{ secrets.GH_TOKEN }}
#
#      - name: Setup postgres
#        run: docker run -d --rm --network host --name postgres -e "POSTGRES_DB=test-scratch" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_PORT=5432" -e "POSTGRES_USER=postgres" ghcr.io/zcaudate-xyz/infra-db:main
#        
#      - name: Run iberia tests
#        run: >
#          docker run --rm --network host -v $(pwd):$(pwd) -w $(pwd) 
#          ghcr.io/zcaudate-xyz/foundation-ci:main 
#          bash -c 'cd statstrade-core && make setup-checkouts && lein test-iberia'

#  run-test-pay:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    timeout-minutes: 5
#
#    steps: 
#      - name: Checkout foundation-base
#        uses: actions/checkout@v3
#        with:
#          repository: zcaudate-xyz/foundation-base
#          path: foundation-base
#          token: ${{ secrets.GH_TOKEN }}
#          
#      - name: Checkout foundation-embed
#        uses: actions/checkout@v3
#        with:
#          repository: zcaudate-xyz/foundation-embed
#          path: foundation-embed
#          token: ${{ secrets.GH_TOKEN }}
#          
#      - name: Checkout foundation-fx
#        uses: actions/checkout@v3
#        with:
#          repository: zcaudate-xyz/foundation-fx
#          path: foundation-fx
#          token: ${{ secrets.GH_TOKEN }}
#          
#      - name: Checkout statstrade-core
#        uses: actions/checkout@v3
#        with:
#          repository: statstrade-dev/statstrade-core
#          path: statstrade-core
#          token: ${{ secrets.GH_TOKEN }}
#          
#      - name: Log into registry ${{ env.REGISTRY }}
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ secrets.GH_USER }}
#          password: ${{ secrets.GH_TOKEN }}
#
#      - name: Setup postgres
#        run: docker run -d --rm --network host --name postgres -e "POSTGRES_DB=test-scratch" -e "POSTGRES_PASSWORD=postgres" -e "POSTGRES_PORT=5432" -e "POSTGRES_USER=postgres" ghcr.io/zcaudate-xyz/infra-db:main
#        
#      - name: Run statspay tests
#        run: >
#          docker run --rm --network host -v $(pwd):$(pwd) -w $(pwd) 
#          ghcr.io/zcaudate-xyz/foundation-ci:main 
#          bash -c 'cd statstrade-core && make setup-checkouts && lein test-pay'
#
