name: Publish Storybook


# Controls when the workflow will run
on:
  repository_dispatch:
    types: [ui-changed]
  workflow_dispatch:

jobs:
    
  publish-storybook:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out monorepo
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          repository: statstrade-dev/statstrade-monorepo
          token: ${{ secrets.GH_TOKEN }} # Personal Access Token with repo write access

      # 2. Install Node and Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 3. Build Storybook
      - name: Build Storybook
        run: yarn storybook:build

      # 4. Publish to statstrade-ui.storybook
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GH_PRIVATE_COMMIT_KEY }} # or token
          external_repository: statstrade-dev/statstrade-ui.storybook
          publish_branch: main
          publish_dir: ./apps/storybook/storybook-static
          user_name: ${{ secrets.GH_USER }}
